### ISSUE TITLE
Allow user to copy

### ISSUE THREAD

**Issue by yangshuairocks** [libgenapps/LibgenDesktop#12]
Right now when you click in the grid, only two menu items are available. 
![image](https://user-images.githubusercontent.com/39968/68729527-30b51b80-0605-11ea-8d82-d1dabda17941.png)
It's more useful to add an item to allow the user to copy the book name. The copied name can be used to search or rename the downloaded file etc.

**Comment by libgenapps** [comment]
Good suggestion! I'll try to implement this in the next release.

**Comment by libgenapps** [comment]
Implemented in 1.4.0.
