### ISSUE TITLE
Does the current version do only NonFiction synchronization?

### ISSUE THREAD

**Issue by omittones** [libgenapps/LibgenDesktop#16]
Based on this code, the app only does NonFiction sync. Is that correct?

https://github.com/libgenapps/LibgenDesktop/blob/04440f2b49a60eeb3e4bfd6942e2ab380f7935d7/LibgenDesktop/ViewModels/Windows/SynchronizationWindowViewModel.cs#L202

**Comment by libgenapps** [comment]
Yes that's correct. Unfortunately, the server side provides only the nonfiction synchronization API.

**Comment by omittones** [comment]
Is there a way to contribute to the project to add the API? I would like to
do it if possible.

**Comment by libgenapps** [comment]
> Is there a way to contribute to the project to add the API? I would like to do it if possible.

That would be a server side change. Unfortunately, I don't know who maintains the server side development and how to contribute to its codebase.
