### ISSUE TITLE
Importing fiction dump from after 2020-02-08 fails on 1.3.5

### ISSUE THREAD

**Issue by RedKage** [libgenapps/LibgenDesktop#19]
Hello there,

Here is the fiction dump `http://gen.lib.rus.ec/dbdumps/fiction_2020-02-17.rar` with extracts to `fiction.sql` with Size: 2368562429 bytes (2258 MiB) and CRC32: A2E42C88.

On a clean install with no database, I select import, then I select `fiction.sql` and at the end I get
![Screenshot_1](https://user-images.githubusercontent.com/11867168/74823992-e6c88980-5307-11ea-99d8-4908aa1ce893.png)

The logs don't give much info
[2020-02-19_11-07-58.log](https://github.com/libgenapps/LibgenDesktop/files/4224382/2020-02-19_11-07-58.log)

**Comment by RedKage** [comment]
Hmmm, this dump `http://gen.lib.rus.ec/dbdumps/fiction_2020-01-11.rar` does import fine
I guess something changed between fiction_2020-01-11 and fiction_2020-02-17

**Comment by RedKage** [comment]
Alright so I narrowed it down, the last working fiction dump is the one from 2020-02-08. Anything after that cannot be imported. Guess the database schema changed or something

**Comment by libgenapps** [comment]
Yes, there has been a database change on the server side on February 12 that affected this particular collection. I'll add the support for the new database dump format in the upcoming version.

**Comment by smaragdus** [comment]
I got the same error when I try to import from [fiction_2020-02-25.rar](http://gen.lib.rus.ec/dbdumps/fiction_2020-02-25.rar):

`Couldn't find the data to import.`

**screen:**

![Libgen Desktop 1 3 5 - 2020-02-26 - error - 001](https://user-images.githubusercontent.com/9025757/75305031-909a9f80-584d-11ea-8819-451ab4c902c8.png)

I hope that a fixed version will be released soon since for the time being [Libgen Desktop](https://github.com/libgenapps/LibgenDesktop) is unusable for me. By the way I discovered the program today and I am glad that it is really portable (configuration and data files saved in program folder).

**Comment by libgenapps** [comment]
@smaragdus, right, sorry about that. The last database dump supported by the current version of LibgenDesktop is **fiction_2020-02-08.rar**. I will try to release the fix by the end of the next week.

**Comment by smaragdus** [comment]
@libgenapps 

Thank you for clarifying which is the last supported dump. Take your time, I am not in a hurry. Actually I am glad that you still maintain Libgen Desktop.

**Comment by libgenapps** [comment]
Due to some unforeseen circumstances I won't be able to release the new version today. The new estimate is the end of the next week.

**Comment by libgenapps** [comment]
Looks like I won't be able release it this week either. I'll do my best to release it around the beginning of April.

**Comment by ekescs** [comment]
Hi, do you have any luck with the new release? Thanks for your efforts :) Stay safe :)

**Comment by libgenapps** [comment]
Sorry for the delay. The last couple months have been kinda erratic.

Support for the new fiction database dump format is completed, I just need to wrap up implementation for a few other features. The release will probably be somewhere around the end of the next week.

**Comment by Elpuma** [comment]
i was able to fix the issue by correcting the GET {link} structure. I'm new in Github, how do I share my code? should I paste it here or elsewhere?

**Comment by RedKage** [comment]
Usually you do this by creating a pull request.
Then, the owner can check your code and decide to reintegrate your branch into the main code. 

However from what I understand, libgenapp has already an unpunished fix for this. 
But, it's still useful to make a PR in my opinion as you may have done things differently than libgenapp

________________________________

**Comment by libgenapps** [comment]
Implemented in 1.4.0.
