### ISSUE TITLE
Do you have a plan to support Mac platform?

### ISSUE THREAD

**Issue by sancao2** [libgenapps/LibgenDesktop#20]

**Comment by smaragdus** [comment]
See #9.

**Comment by libgenapps** [comment]
@sancao2, yes for LibgenServer: https://github.com/libgenapps/LibgenServer, no for LibgenDesktop. LibgenDesktop is written on WPF (Windows Presentation Foundation) which is not portable to Mac or Linux. If someone were to port LibgenDesktop to Mac, that would be a completely new app.
