### ISSUE TITLE
Suggestion: Possible Android Port? 

### ISSUE THREAD

**Issue by h3xpl01t** [libgenapps/LibgenDesktop#22]
Hey, I'm not sure how to style this, I don't often submit issues to projects. But I was wondering if you had considered making an Android port ofthe app. Its super useful to me on Desktop and I'd love to access it on my phone too. I know most Android apps are made in Java though. Maybe adding an option for a self-hosted web interface to the Desktop app would be an easier ask?

**Comment by h3xpl01t** [comment]
Hey, I'm not sure how to style this, I don't often submit issues to projects. But I was wondering if you had considered making an Android port ofthe app. Its super useful to me on Desktop and I'd love to access it on my phone too. I know most Android apps are made in Java though. Maybe adding an option for a self-hosted web interface to the Desktop app would be an easier ask?

**Comment by libgenapps** [comment]
LibgenDesktop is written on WPF (Windows Presentation Foundation) which is not available anywhere outside Windows, so if someone were to port LibgenDesktop to Android, that would be a completely new app. Android client however is planned for LibgenServer: https://github.com/libgenapps/LibgenServer.
