### ISSUE TITLE
Do you have a version for MacOS? 

### ISSUE THREAD

**Issue by magshaban** [libgenapps/LibgenDesktop#23]
Do you have a version for MacOS?

**Comment by libgenapps** [comment]
Duplicate of https://github.com/libgenapps/LibgenDesktop/issues/5, https://github.com/libgenapps/LibgenDesktop/issues/8, https://github.com/libgenapps/LibgenDesktop/issues/9, and https://github.com/libgenapps/LibgenDesktop/issues/20.
