### ISSUE TITLE
How to change default columns order

### ISSUE THREAD

**Issue by Elpuma** [libgenapps/LibgenDesktop#30]
- [X] I understand that feature requests are no longer accepted except for those listed here: https://github.com/libgenapps/LibgenDesktop/issues/27

Choose one of the following:
- [X] this is a bug report;
- [ ] this is a new translation suggestion.

I have been trying with no success to change the default column order, from Title+Authors+Series+Year... to Title+Authors+Year(in ascending order)+Format+... But so far I can't find the piece of code that impacts the order! Is it in this order already on the database or is it chosen by any configuration file? In all humbleness and as an absolute rookie learner I'm looking for guidance on this matter.

I know how to add options to the "settings" menu, I intend to put order selectors in the setting menu so one can sort them and save it in the configuration file as default, but I'm stuck midway.

**Comment by libgenapps** [comment]
While you can change the order of the columns (by dragging their headers) the order is currently not persisted anywhere. However, this is part of the "search results column set customization" item in the roadmap you referenced in your message.
