### ISSUE TITLE
Windows Regional Format Settings Ignored

### ISSUE THREAD

**Issue by VaslD** [libgenapps/LibgenDesktop#6]
I'm working on localization (will PR soon) and I have found an annoying date/time display bug.

On my computer I have Windows display language set to my native language so I have familiar UI texts and units of measurement; but I changed Regional Format (from *Settings > Time & Language & Region*, it's a dedicated setting to tell Windows how to format date and time strings) to match the locale where I stay to get my colleague readable auto timestamps on my work.

When setting Libgen to use Windows display language, Libgen uses the string specifier read from corresponding language file, which I set to `yyyy 年 M 月 d 日 tt hh:mm:ss` for Simplified Chinese. This will work if the Regional Format matches UI language (set to Chinese, China), it translates to "2019 年 8 月 7 日 下午 5:35" or something like that.

<img width="324" alt="Annotation 2019-08-07 173724" src="https://user-images.githubusercontent.com/3415065/62613939-07695d00-b93d-11e9-9758-b4521af84673.png">

But my Regional Format is different, and the string becomes "2019 年 8 月 7 日 PM 5:36":

<img width="364" alt="Annotation 2019-08-07 175612" src="https://user-images.githubusercontent.com/3415065/62613769-b35e7880-b93c-11e9-97a6-dea7be99a5a9.png">

<img width="324" alt="Annotation 2019-08-07 174009" src="https://user-images.githubusercontent.com/3415065/62613949-0df7d480-b93d-11e9-9d26-0404b7f514fe.png">

This is because Windows (and .NET) itself correctly uses English (Hong Kong SAR) for those date/time specifiers (`yyyy`, `M`, `tt`, etc.) although the UI language is different. Just so happens that everything else besides `tt` are both plain numbers in both Chinese and English.

Currently it isn't such a big deal but dead annoying to look at when dates are everywhere. It will become unreadable when a language uses a different numbering system for dates, or never uses 12-hour clock (`tt` returns empty string). **One solution I can think of is to use localized dates ONLY when Regional Format matches UI language, otherwise let Windows deals with it by using a default short specifier (such as, `g`).**

**Comment by libgenapps** [comment]
Does the second option here: https://dotnetfiddle.net/0aUpWT look correct? If it does, then we can just take the culture code from the language file itself to format the dates and times.

**Comment by VaslD** [comment]
Good idea. The code you posted works as well.

The only downside being that it still doesn't follow user's regional settings. But since they choose to use a specific language, I guess it's OK to assume they want dates in that language too.
