### ISSUE TITLE
Any chance of future linux support?

### ISSUE THREAD

**Issue by duodecillian** [libgenapps/LibgenDesktop#8]

**Comment by libgenapps** [comment]
Duplicate of https://github.com/libgenapps/LibgenDesktop/issues/5.

The code base is about 80-90 percent Windows-specific so adding Linux support is almost the same as writing a new app.

As a matter of fact, there is a web app currently being developed that may potentially have Linux support in the future: https://github.com/libgenapps/LibgenServer.
