### ISSUE TITLE
Library Genesis for Mac

### ISSUE THREAD

**Issue by yiranzhimo** [libgenapps/LibgenDesktop#9]
Dear Developer, do you have the plan to design this for Mac platform?
Thank you!

**Comment by strike65** [comment]
I'll try to port the app to macOS. Will Need some time.

**Comment by libgenapps** [comment]
@yiranzhimo, not for LibgenDesktop. But https://github.com/libgenapps/LibgenServer will have support for Windows, Linux, and MacOS.

**Comment by bendtherules** [comment]
On mac, my current approach is to download [sql dump](https://data.library.bz/dbdumps/) and then open it with Mysql.
